

--Ejercicios Combinación de Tablas - Extra
--Tablas del usuario HR


--tabla COUNTRIES
COUNTRY_ID	CHAR(2 BYTE)	No		1	Primary key of countries table.
COUNTRY_NAME	VARCHAR2(40 BYTE)	Yes		2	Country name
REGION_ID	NUMBER	Yes		3	Region ID for the country. Foreign key to region_id column in the departments table.

--TABLA DEPARTMENTS
DEPARTMENT_ID	NUMBER(4,0)	No		1
DEPARTMENT_NAME	VARCHAR2(30 BYTE)	No		2
MANAGER_ID	NUMBER(6,0)	Yes		3
LOCATION_ID	NUMBER(4,0)	Yes		4

--TABLA EMPLOYEES
EMPLOYEE_ID	NUMBER(6,0)	No	
FIRST_NAME	VARCHAR2(20 BYTE)	Yes	
LAST_NAME	VARCHAR2(25 BYTE)	No	
EMAIL	VARCHAR2(25 BYTE)	No	
PHONE_NUMBER	VARCHAR2(20 BYTE)	Yes	
HIRE_DATE	DATE	No	
JOB_ID	VARCHAR2(10 BYTE)	No	
SALARY	NUMBER(8,2)	Yes	
COMMISSION_PCT	NUMBER(2,2)	Yes	
MANAGER_ID	NUMBER(6,0)	Yes	
DEPARTMENT_ID	NUMBER(4,0)	Yes	

--TABLA JOB_HISTORY
EMPLOYEE_ID	NUMBER(6,0)	No	
START_DATE	DATE	No	
END_DATE	DATE	No	
JOB_ID	VARCHAR2(10 BYTE)	No	
DEPARTMENT_ID	NUMBER(4,0)	Yes	

--TABLA JOBS
JOB_ID	VARCHAR2(10 BYTE)	No		1
JOB_TITLE	VARCHAR2(35 BYTE)	No		2
MIN_SALARY	NUMBER(6,0)	Yes		3
MAX_SALARY	NUMBER(6,0)	Yes		4

--TABLA LOCATIONS
LOCATION_ID	NUMBER(4,0)	No		1
STREET_ADDRESS	VARCHAR2(40 BYTE)	Yes		2
POSTAL_CODE	VARCHAR2(12 BYTE)	Yes		3
CITY	VARCHAR2(30 BYTE)	No		4
STATE_PROVINCE	VARCHAR2(25 BYTE)	Yes		5
COUNTRY_ID	CHAR(2 BYTE)	Yes		6


--TABLA REGIONS
REGION_ID	NUMBER	No		1	
REGION_NAME	VARCHAR2(25 BYTE)	Yes		2	


--1. Muestra el código y nombre de todos los departamentos junto al nombre de la ciudad donde se encuentran. TABLA LOCATIONS

SELECT DEP.DEPARTMENT_ID , DEP.DEPARTMENT_NAME, LOC.CITY
FROM DEPARTMENTS DEP
JOIN LOCATIONS LOC ON DEP.LOCATION_ID = LOC.LOCATION_ID;


--2. Añade a los resultados de la consulta anterior, el nombre del país.

SELECT DEP.DEPARTMENT_ID , DEP.DEPARTMENT_NAME, LOC.CITY, COU.COUNTRY_NAME
FROM DEPARTMENTS DEP
JOIN LOCATIONS LOC ON DEP.LOCATION_ID = LOC.LOCATION_ID
JOIN COUNTRIES COU ON LOC.COUNTRY_ID = COU.COUNTRY_ID; --VINCULACION CON EL OTRO JOIN, EN VEZ DE CON FROM


--3. Muestra la información de las consultas anteriores pero únicamente de EEUU (‘United States of America’)
--NO RETORNA NINGUN RESULTADO
SELECT DEP.DEPARTMENT_ID , DEP.DEPARTMENT_NAME, LOC.CITY
FROM DEPARTMENTS DEP
JOIN LOCATIONS LOC ON DEP.LOCATION_ID = LOC.LOCATION_ID
JOIN COUNTRIES COU ON LOC.COUNTRY_ID = COU.COUNTRY_ID
WHERE UPPER(COUNTRY_NAME) IN ('UNITED STATES OF AMAERICA');

--4. Muestra de cada empleado su nombre, apellido y los diferentes empleos (JOB_TITLE) por los que ha pasado utilizando la tabla JOB_HISTORY

SELECT DISTINCT EMP.EMPLOYEE_ID , EMP.FIRST_NAME, EMP.LAST_NAME, J.JOB_TITLE
FROM EMPLOYEES EMP
JOIN JOB_HISTORY HIS ON EMP.JOB_ID = HIS.JOB_ID
JOIN JOBS J ON EMP.JOB_ID = J.JOB_ID;


--TABLA EMPLOYEES
EMPLOYEE_ID	NUMBER(6,0)	No	
FIRST_NAME	VARCHAR2(20 BYTE)	Yes	
LAST_NAME	VARCHAR2(25 BYTE)	No	
EMAIL	VARCHAR2(25 BYTE)	No	
PHONE_NUMBER	VARCHAR2(20 BYTE)	Yes	
HIRE_DATE	DATE	No	
JOB_ID	VARCHAR2(10 BYTE)	No	
SALARY	NUMBER(8,2)	Yes	
COMMISSION_PCT	NUMBER(2,2)	Yes	
MANAGER_ID	NUMBER(6,0)	Yes	
DEPARTMENT_ID	NUMBER(4,0)	Yes	

--TABLA JOB_HISTORY
EMPLOYEE_ID	NUMBER(6,0)	No	
START_DATE	DATE	No	
END_DATE	DATE	No	
JOB_ID	VARCHAR2(10 BYTE)	No	
DEPARTMENT_ID	NUMBER(4,0)	Yes	

--TABLA JOBS
JOB_ID	VARCHAR2(10 BYTE)	No		1
JOB_TITLE	VARCHAR2(35 BYTE)	No		2
MIN_SALARY	NUMBER(6,0)	Yes		3
MAX_SALARY	NUMBER(6,0)	Yes		4

--no hacer aun
--5. Selecciona de la consulta anterior los nombres y apellidos de aquellos empleados que aparecen al menos 2 veces en el histórico de empleos.


--6. Muestra el nombre y apellido de todos los empleados que son representantes de ventas (‘Sales Representative’)

SELECT DISTINCT EMP.FIRST_NAME, EMP.LAST_NAME 
FROM EMPLOYEES EMP
JOIN JOBS J ON EMP.JOB_ID = J.JOB_ID
WHERE UPPER(JOB_TITLE) LIKE '%SALES REPRESENTATIVE%'

--7. Muestra el nombre, apellido y salario de los empleados junto al nombre del empleo que desarrolla, salarios mínimo y máximo establecidos para su empleo.
--NO SE RESOLVERLA
SELECT EMP.FIRST_NAME, EMP.LAST_NAME, J.JOB_TITLE, EMP.SALARY,
CASE WHEN J.JOB_TITTLE 
FROM EMPLOYEES EMP
JOIN JOBS J ON EMP.JOB_ID = J.JOB_ID



--8. De la consulta anterior obtén el nombre y apellido de los empleados que cobran el salario máximo que se designa a su empleo.
--NO SE RESOLVER

--no hacer aun
--9. Muestra el nombre y apellido de empleados que tengan a su cargo al menos a 5 empleados.


--PREGUNTAR EN CLASE NO RETORNA NADA
--10. Muestra el nombre de empleados que trabajen en Europa (‘Europe’)
--TABLA LOCATIONS
STREET_ADDRESS	VARCHAR2(40 BYTE)	Yes		2
POSTAL_CODE	VARCHAR2(12 BYTE)	Yes		3
CITY	VARCHAR2(30 BYTE)	No		4
STATE_PROVINCE	VARCHAR2(25 BYTE)	Yes		5
COUNTRY_ID	CHAR(2 BYTE)	Yes		6
--tabla COUNTRIES
COUNTRY_ID	CHAR(2 BYTE)	No		1	Primary key of countries table.
COUNTRY_NAME	VARCHAR2(40 BYTE)	Yes		2	Country name
REGION_ID	NUMBER	Yes		3	Region ID for the country. Foreign key to region_id column in the departments table.
--TABLA REGIONS
REGION_ID	NUMBER	No		1	
REGION_NAME	VARCHAR2(25 BYTE)	Yes		2	


--TABLA DEPARTMENTS
DEPARTMENT_ID	NUMBER(4,0)	No		1
DEPARTMENT_NAME	VARCHAR2(30 BYTE)	No		2
MANAGER_ID	NUMBER(6,0)	Yes		3
LOCATION_ID	NUMBER(4,0)	Yes		4 

--TABLA EMPLOYEES
EMPLOYEE_ID	NUMBER(6,0)	No	
FIRST_NAME	VARCHAR2(20 BYTE)	Yes	
LAST_NAME	VARCHAR2(25 BYTE)	No	
EMAIL	VARCHAR2(25 BYTE)	No	
PHONE_NUMBER	VARCHAR2(20 BYTE)	Yes	
HIRE_DATE	DATE	No	
JOB_ID	VARCHAR2(10 BYTE)	No	
SALARY	NUMBER(8,2)	Yes	
COMMISSION_PCT	NUMBER(2,2)	Yes	
MANAGER_ID	NUMBER(6,0)	Yes	
DEPARTMENT_ID	NUMBER(4,0)	Yes	


SELECT EMP.FIRST_NAME 
FROM EMPLOYEES EMP
JOIN DEPARTMENTS DEPART ON EMP.DEPARTMENT_ID = DEPART.DEPARTMENT_ID --EMPLEADOS UNE A DE PARTAMENTOS
JOIN LOCATIONS LOC ON DEPART.LOCATION_ID = LOC.LOCATION_ID-- DEPARTAMENTOS UNE A LOCALIDADES
JOIN COUNTRIES COU ON COU.COUNTRY_ID = LOC.COUNTRY_ID --UNE LOCALIDADES CON PAISES
JOIN REGIONS REG ON REG.REGION_ID = COU.REGION_ID --UNE PAISES CON REGIONES
WHERE UPPER(REG.REGION_NAME) LIKE 'EUROPA';

--11. Muestra el nombre de empleados que trabajen en departamentos de recursos humanos de Europa (‘Human Resources’).
--IGUAL NO RETORNA NINGUN RESULTADO
SELECT EMP.FIRST_NAME 
FROM EMPLOYEES EMP
JOIN DEPARTMENTS DEPART ON EMP.DEPARTMENT_ID = DEPART.DEPARTMENT_ID --EMPLEADOS UNE A DE PARTAMENTOS
JOIN LOCATIONS LOC ON DEPART.LOCATION_ID = LOC.LOCATION_ID-- DEPARTAMENTOS UNE A LOCALIDADES
JOIN COUNTRIES COU ON COU.COUNTRY_ID = LOC.COUNTRY_ID --UNE LOCALIDADES CON PAISES
JOIN REGIONS REG ON REG.REGION_ID = COU.REGION_ID --UNE PAISES CON REGIONES
WHERE UPPER(REG.REGION_NAME) LIKE 'EUROPA' AND UPPER(DEPART.DEPARTMENT_NAME) LIKE 'HUMAN RESOURCES';

--no hacer aun
--12. Muestra de cada país su nombre y la suma salarial de todos su trabajadores.

--13. Muestra de cada departamento su nombre y la suma de las comisiones que cobran sus empleados. Aquellos departamentos cuyos empleados no cobren
--comisión, deben aparecer con comisión 0





