

REM ********** TABLA MISTEXTOS: *************

DROP TABLE MISTEXTOS cascade constraints; 

CREATE TABLE MISTEXTOS (
 TITULO  VARCHAR2(32),
 AUTOR   VARCHAR2(22),
 EDITORIAL VARCHAR2(15), 
 PAGINA  NUMBER(3)
 ) ;

INSERT INTO MISTEXTOS VALUES ('METODOLOGiA DE LA PROGRAMACION.', 'ALCALDE GARCIA', 'MCGRAWHILL',140);
INSERT INTO MISTEXTOS VALUES ('"INFORMOTICA BASICA."', 'GARCIA GARCERON', 'PARANINFO',130);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS OPERATIVOS', 'GARCIA STRUCH', 'OBSBORNE',300);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS DIGITALES.', 'RUIZ LOPEZ','PRENTICE HALL',190);
INSERT INTO MISTEXTOS VALUES ('"MANUAL DE C."', 'RUIZ LOPEZ', 'MCGRAWHILL',340);

COMMIT;

--1. Mostrar el título sin comillas y los tres primeros caracteres de la editorial.


SELECT TITULO, TRIM(BOTH '"' FROM TITULO) AS NEW_TITTLE, SUBSTR(EDITORIAL,1,3) AS EDITORIAL
FROM MISTEXTOS;



--2. Mostrar el título sin punto ni comillas y la editorial en minúsculas.

--NO FUNCIONA Y DEBERIA SUSTITUOT POR ESACIOS VACIOS AL NO PASAR NINGUN PARAMETRO
--NO FUNCIONA TRANSLATE PORQUE AL MENOS UNO DE LOS CARACTERES TIENE QUE TENER UN TERCER PARAMETRO QUE LOS SUSTITUYA
SELECT TITULO, TRANSLATE(TITULO, '."') AS NEW_TITTLE, LOWER(EDITORIAL) AS EDITORIAL_MINUS
FROM MISTEXTOS;

SELECT RTRIM(RTRIM(LTRIM(TITULO, '"'), '"'), '.'),LOWER(EDITORIAL) FROM MISTEXTOS;

SELECT REPLACE(REPLACE(TITULO, '"'), '.'), LOWER (EDITORIAL) FROM MISTEXTOS;




--3. Mostrar los títulos de la siguiente manera
--ESTA PIDIENDO QUE PONGAMOS LA PRIMERA EN MAYUS Y LAS DEMAAS EN MINUSCULA, ADEMAS DE ELIMINAR LAS COMAS Y LOS PUNTOS
SELECT INITCAP (TITULO) AS NEW_TITTLE 
FROM MISTEXTOS;


--4. Mostrarel título que más páginas tiene. (RESULTADO CORRECTO)

SELECT TITULO, PAGINA 
FROM MISTEXTOS
WHERE PAGINA = (SELECT MAX(PAGINA) FROM MISTEXTOS);


--5. Mostrar el autor concatenado con *** y con la editorial y ordenado por el número de caracteres de la editorial.

--NO COMPILA
SELECT AUTOR + '***' + EDITORIAL 
FROM MISTEXTOS
ORDER BY EDITORIAL = (SELECT LENGTH(EDITORIAL) FROM MISTEXTOS);

--CONCADENAR CADENAS
SELECT CONCAT(CONCAT(AUTOR, '***'),EDITORIAL) 
FROM MISTEXTOS
ORDER BY LENGTH (EDITORIAL);


REM ********** TABLA LIBROS: *************

DROP TABLE LIBROS cascade constraints; 

CREATE TABLE LIBROS (
 TITULO  VARCHAR2(32),
 AUTOR   VARCHAR2(22),
 EDITORIAL VARCHAR2(15), 
 PAGINA  NUMBER(3)
 ) ;

INSERT INTO LIBROS VALUES ('LA COLMENA', 'CELA, CAMILO JOSE', 'PLANETA',240);
INSERT INTO LIBROS VALUES ('LA HISTORIA DE MI HIJO', 'GORDIMER, NADINE', 'TIEM.MODERNOS',327);
INSERT INTO LIBROS VALUES ('LA MIRADA DEL OTRO', 'G.DELGADO, FERNANDO', 'PLANETA',298);
INSERT INTO LIBROS VALUES ('ULTIMAS TARDES CON TERESA','MARSE, JUAN', 'CIRCULO',350);
INSERT INTO LIBROS VALUES ('LA NOVELA DE P. ANSUREZ', 
'TORRENTE B., GONZALO', 'PLANETA',162);
COMMIT;


--6.Escribir la sentencia SELECT que visualice dos columnas, una con el AUTOR y otra con el apellido del autor.

-- EL NOMBRE VA DESDE EL PRIMER CARACTER , INSTR BUSCA EL CARACTER VACIO Y LE RESTA UNO (-1) --> NOMBRE
--EL APELLIDO ESL SUBSTR EMPIEZA EN EL ESPACIO QUE INSTR ENCUENTRE EN ' ' Y LE SUMA UNO (+1) --> APELLIDO
SELECT SUBSTR(AUTOR, 1, INSTR (AUTOR,' ' )-1) AS NOMBRE_AUTOR, SUBSTR(AUTOR,INSTR(AUTOR, ' ')+1)AS AUTOR_APELLIDO
FROM LIBROS; 

--7. Escribir la sentencia SELECT que visualice las columnas de AUTOR y otra columna con el nombre del autor (sin el apellido)


SELECT AUTOR, SUBSTR(AUTOR, INSTR (AUTOR, ',')+2) AS NOMBRE_AUTOR
FROM LIBROS; 

--8. Escribir la sentencia SELECT que visualice las columnas de AUTOR y otra columna con el nombre y luego el apellido del autor

SELECT AUTOR, 
CONCAT(CONCAT(SUBSTR(AUTOR, INSTR (AUTOR, ',')+2), ' ' AS NOMBRE_AUTOR,  SUBSTR(AUTOR,1, INSTR (AUTOR, ',')+2) AS NOMBRE_AUTOR

SELECT AUTOR, 
SUBSTR(AUTOR, INSTR(AUTOR,',') +2) || ' ' || SUBSTR(AUTOR,1,INSTR(AUTOR, ',')-1)
FROM LIBROS;

--9. Mostrar los cuatro primeros caracteres del autor que menos caracteres tiene
---NOS CHUVA QUE QUIEN TIENE MENOS CARACTERES ES MARSE, JUAN
SELECT LENGTH(AUTOR) AS TAMANIO, AUTOR
FROM LIBROS;

--NO DA EL RESULTADO CORRECTO, PARECE QUE MIN, NO FUNCIONA
SELECT SUBSTR(AUTOR, 1, 4) AS RESULTADO, LENGTH(AUTOR) AS CARACTERES_AUTOR
FROM LIBROS
WHERE LENGTH(AUTOR) = (SELECT MIN(AUTOR) FROM LIBROS);

--TAAMPOCO SOLUCIONA
SELECT SUBSTR(AUTOR, 1, 4) AS RESULTADO, LENGTH(AUTOR) AS CARACTERES_AUTOR
FROM LIBROS
WHERE UPPER(AUTOR) < (SELECT LENGTH(AUTOR) FROM LIBROS);

--SOLUCION 
SELECT SUBSTR(AUTOR, 1, 4) AS RESULTADO
FROM LIBROS
WHERE LENGTH(AUTOR) = (SELECT MIN(LENGTH(AUTOR)) FROM LIBROS);


--10. Mostrar los tres últimos caracteres de la editorial y título en tipo ”título” de los libros con más páginas que la media
--NO ENTIENDO PORQUE NO COCGE LOS TRES ULTIMOS CARACTERES
SELECT EDITORIAL, SUBSTR(EDITORIAL, -1, 3) AS ULTIMO_CARACTERES, INITCAP(TITULO)
FROM LIBROS
WHERE PAGINA > (SELECT AVG(PAGINA)  FROM LIBROS);

--SOLUCCION

SELECT SUBSTR (EDITORIAL, -3), INITCAP(TITULO)
FROM LIBROS
WHERE PAGINA > (SELECT AVG(PAGINA) FROM LIBROS);
